-- SEED VOL.1: lessons
INSERT INTO lessons (lesson_number, volume, title_ko, title_fr, topic_ko, topic_fr) VALUES
  (1, 1, '저는 대학생이에요', 'Je suis étudiant(e) à l''université', '소개하기', 'Se présenter'),
  (2, 1, '어디에 가요?', 'Où allez-vous ?', '장소와 행동', 'Lieux et actions'),
  (3, 1, '전화번호가 뭐예요?', 'Quel est votre numéro de téléphone ?', '숫자와 전화번호', 'Chiffres et numéros de téléphone'),
  (4, 1, '책상 위에 지갑이 있어요', 'Il y a un portefeuille sur le bureau', '위치 말하기', 'Indiquer l''emplacement'),
  (5, 1, '사과하고 오렌지가 맛있어요', 'Les pommes et les oranges sont délicieuses', '물건 사기', 'Faire des achats'),
  (6, 1, '저는 비빔냉면을 좋아해요', 'J''aime le bibim naengmyeon', '음식 주문하기', 'Commander de la nourriture'),
  (7, 1, '토요일에 뭐 해요?', 'Que faites-vous samedi ?', '날짜 요일 시간', 'Dates, jours et heures'),
  (8, 1, '도서관에서 뭐 했어요?', 'Qu''avez-vous fait à la bibliothèque ?', '과거 경험 말하기', 'Parler d''expériences passées'),
  (9, 1, '다음 주말에 같이 축구해요', 'Jouons au football ensemble le week-end prochain', '취미와 약속', 'Loisirs et rendez-vous'),
  (10, 1, '낚시를 하러 갔어요', 'Je suis allé(e) pêcher', '가족 소개', 'Présenter sa famille'),
  (11, 1, '콘서트를 보러 갈까요?', 'Allons-nous voir un concert ?', '약속 정하기', 'Prendre rendez-vous'),
  (12, 1, '좀 춥고 눈도 많이 올 거예요', 'Il fait un peu froid et il neigera beaucoup', '날씨 추측하기', 'Parler de la météo / déduire'),
  (13, 1, '어머니께 선물할 거예요', 'Je vais offrir un cadeau à ma mère', '색깔과 옷', 'Couleurs et vêtements'),
  (14, 1, '배가 너무 불러서 베트남 음식을 못 먹었어요', 'J''étais tellement rassasié(e) que je ne pouvais pas manger de nourriture vietnamienne', '이유 말하기', 'Expliquer une raison');

-- SEED VOL.1: items
INSERT INTO items (lesson_number, volume, type, korean, french, grammar_explanation, grammar_form_note, example_sentence, sort_order) VALUES
  (1, 1, 'vocabulary', '대학생', 'étudiant(e) à l''université', '', '', '', 1),
  (1, 1, 'vocabulary', '학생', 'étudiant(e) / élève', '', '', '', 2),
  (1, 1, 'vocabulary', '선생님', 'professeur / enseignant(e)', '', '', '', 3),
  (1, 1, 'vocabulary', '회사원', 'employé(e) de bureau', '', '', '', 4),
  (1, 1, 'vocabulary', '의사', 'médecin', '', '', '', 5),
  (1, 1, 'vocabulary', '요리사', 'cuisinier / chef cuisinier', '', '', '', 6),
  (1, 1, 'vocabulary', '경찰', 'policier', '', '', '', 7),
  (1, 1, 'vocabulary', '가수', 'chanteur / chanteuse', '', '', '', 8),
  (1, 1, 'vocabulary', '영화배우', 'acteur / actrice', '', '', '', 9),
  (1, 1, 'vocabulary', '운동선수', 'sportif / athlète', '', '', '', 10),
  (1, 1, 'vocabulary', '변호사', 'avocat(e)', '', '', '', 11),
  (1, 1, 'vocabulary', '한국', 'Corée', '', '', '', 12),
  (1, 1, 'vocabulary', '중국', 'Chine', '', '', '', 13),
  (1, 1, 'vocabulary', '일본', 'Japon', '', '', '', 14),
  (1, 1, 'vocabulary', '미국', 'États-Unis', '', '', '', 15),
  (1, 1, 'vocabulary', '호주', 'Australie', '', '', '', 16),
  (1, 1, 'vocabulary', '영국', 'Angleterre', '', '', '', 17),
  (1, 1, 'vocabulary', '프랑스', 'France', '', '', '', 18),
  (1, 1, 'vocabulary', '베트남', 'Viêtnam', '', '', '', 19),
  (1, 1, 'vocabulary', '브라질', 'Brésil', '', '', '', 20),
  (1, 1, 'vocabulary', '멕시코', 'Mexique', '', '', '', 21),
  (1, 1, 'vocabulary', '인도', 'Inde', '', '', '', 22),
  (1, 1, 'vocabulary', '케냐', 'Kenya', '', '', '', 23),
  (1, 1, 'vocabulary', '이탈리아', 'Italie', '', '', '', 24),
  (1, 1, 'vocabulary', '이집트', 'Égypte', '', '', '', 25),
  (1, 1, 'vocabulary', '카자흐스탄', 'Kazakhstan', '', '', '', 26),
  (1, 1, 'vocabulary', '이름', 'nom / prénom', '', '', '', 27),
  (1, 1, 'vocabulary', '국적', 'nationalité', '', '', '', 28),
  (1, 1, 'vocabulary', '직업', 'profession / métier', '', '', '', 29),
  (1, 1, 'expression', '안녕하세요?', 'bonjour', '', '', '', 1),
  (1, 1, 'expression', '저는 ~이에요/예요', 'je suis ~', '', '', '', 2),
  (1, 1, 'expression', '만나서 반가워요', 'ravi(e) de vous rencontrer', '', '', '', 3),
  (1, 1, 'expression', '무슨 일 하세요?', 'que faites-vous dans la vie ?', '', '', '', 4),
  (1, 1, 'expression', '어느 나라 사람이에요?', 'de quelle nationalité êtes-vous ?', '', '', '', 5),
  (1, 1, 'expression', '어디에서 왔어요?', 'd''où venez-vous ?', '', '', '', 6),
  (1, 1, 'grammar', '이에요/예요', 'S''attache à un nom pour former une phrase déclarative ou interrogative (=est/suis/es)', 'S''attache à un nom pour former une phrase déclarative ou interrogative (=est/suis/es)', '이에요 après consonne, 예요 après voyelle', '저는 학생이에요 (Je suis étudiant) / 마크예요 (C''est Mark)', 1),
  (1, 1, 'grammar', '은/는', 'Indique le thème ou le sujet de la phrase, peut aussi marquer un contraste', 'Indique le thème ou le sujet de la phrase, peut aussi marquer un contraste', '은 après consonne, 는 après voyelle', '저는 한국 사람이에요 (Moi, je suis coréen)', 2),
  (2, 1, 'vocabulary', '식당', 'restaurant', '', '', '', 1),
  (2, 1, 'vocabulary', '카페', 'café', '', '', '', 2),
  (2, 1, 'vocabulary', '회사', 'entreprise / bureau', '', '', '', 3),
  (2, 1, 'vocabulary', '세종학당', 'Institut du Roi Sejong', '', '', '', 4),
  (2, 1, 'vocabulary', '사무실', 'bureau / salle de travail', '', '', '', 5),
  (2, 1, 'vocabulary', '화장실', 'toilettes', '', '', '', 6),
  (2, 1, 'vocabulary', '집', 'maison / chez soi', '', '', '', 7),
  (2, 1, 'vocabulary', '옷 가게', 'magasin de vêtements', '', '', '', 8),
  (2, 1, 'vocabulary', '도서관', 'bibliothèque', '', '', '', 9),
  (2, 1, 'vocabulary', '병원', 'hôpital', '', '', '', 10),
  (2, 1, 'vocabulary', '마트', 'supermarché', '', '', '', 11),
  (2, 1, 'vocabulary', '공원', 'parc', '', '', '', 12),
  (2, 1, 'vocabulary', '놀이공원', 'parc d''attractions', '', '', '', 13),
  (2, 1, 'vocabulary', '헬스클럽', 'salle de sport', '', '', '', 14),
  (2, 1, 'vocabulary', '쉬어요', 'se reposer', '', '', '', 15),
  (2, 1, 'vocabulary', '먹어요', 'manger', '', '', '', 16),
  (2, 1, 'vocabulary', '운동해요', 'faire du sport', '', '', '', 17),
  (2, 1, 'vocabulary', '마셔요', 'boire', '', '', '', 18),
  (2, 1, 'vocabulary', '전화해요', 'téléphoner', '', '', '', 19),
  (2, 1, 'vocabulary', '자요', 'dormir', '', '', '', 20),
  (2, 1, 'vocabulary', '가요', 'aller', '', '', '', 21),
  (2, 1, 'vocabulary', '와요', 'venir', '', '', '', 22),
  (2, 1, 'vocabulary', '읽어요', 'lire', '', '', '', 23),
  (2, 1, 'vocabulary', '이야기해요', 'parler / discuter', '', '', '', 24),
  (2, 1, 'vocabulary', '공부해요', 'étudier', '', '', '', 25),
  (2, 1, 'vocabulary', '일해요', 'travailler', '', '', '', 26),
  (2, 1, 'vocabulary', '결혼하다', 'se marier', '', '', '', 27),
  (2, 1, 'vocabulary', '회의', 'réunion', '', '', '', 28),
  (2, 1, 'vocabulary', '파티', 'fête', '', '', '', 29),
  (2, 1, 'vocabulary', '오랜만이에요', 'cela fait longtemps', '', '', '', 30),
  (2, 1, 'vocabulary', '그래요?', 'ah bon ?', '', '', '', 31),
  (2, 1, 'vocabulary', '잘 다녀와요', 'bon voyage / bonne journée', '', '', '', 32),
  (2, 1, 'expression', '지금 어디에 가요?', 'où allez-vous maintenant ?', '', '', '', 1),
  (2, 1, 'expression', '오늘 뭐 해요?', 'que faites-vous aujourd''hui ?', '', '', '', 2),
  (2, 1, 'expression', '같이 가요', 'allons-y ensemble', '', '', '', 3),
  (2, 1, 'expression', '내일 봐요', 'à demain', '', '', '', 4),
  (2, 1, 'expression', '바쁘다', 'être occupé(e)', '', '', '', 5),
  (2, 1, 'grammar', '-아요/-어요/-여요 (1)', 'Décrit une action ou un état au présent. Terminaison informelle', 'Décrit une action ou un état au présent. Terminaison informelle', '아요 si voyelle ㅏ/ㅗ, 어요 sinon, 여요 pour 하다 (→해요)', '지금 뭐 해요? (Que faites-vous ?) / 밥 먹어요 (Je mange)', 1),
  (2, 1, 'grammar', '에 가요', 'Exprime un mouvement vers une direction ou une destination', 'Exprime un mouvement vers une direction ou une destination', '에 가요 = s''éloigner / 에 와요 = se rapprocher / 에 다녀요 = fréquenter', '회사에 가요 (Je vais au bureau) / 세종학당에 다녀요 (Je fréquente l''Institut Sejong)', 2),
  (3, 1, 'vocabulary', '일', '1 (un)', '', '', '', 1),
  (3, 1, 'vocabulary', '이', '2 (deux)', '', '', '', 2),
  (3, 1, 'vocabulary', '삼', '3 (trois)', '', '', '', 3),
  (3, 1, 'vocabulary', '사', '4 (quatre)', '', '', '', 4),
  (3, 1, 'vocabulary', '오', '5 (cinq)', '', '', '', 5),
  (3, 1, 'vocabulary', '육', '6 (six)', '', '', '', 6),
  (3, 1, 'vocabulary', '칠', '7 (sept)', '', '', '', 7),
  (3, 1, 'vocabulary', '팔', '8 (huit)', '', '', '', 8),
  (3, 1, 'vocabulary', '구', '9 (neuf)', '', '', '', 9),
  (3, 1, 'vocabulary', '십', '10 (dix)', '', '', '', 10),
  (3, 1, 'vocabulary', '백', '100 (cent)', '', '', '', 11),
  (3, 1, 'vocabulary', '천', '1000 (mille)', '', '', '', 12),
  (3, 1, 'vocabulary', '만', '10 000 (dix mille)', '', '', '', 13),
  (3, 1, 'vocabulary', '영/공', '0 (zéro)', '', '', '', 14),
  (3, 1, 'vocabulary', '전화번호', 'numéro de téléphone', '', '', '', 15),
  (3, 1, 'vocabulary', '아파트', 'appartement', '', '', '', 16),
  (3, 1, 'vocabulary', '살다', 'habiter / vivre', '', '', '', 17),
  (3, 1, 'vocabulary', '이사 오다', 'emménager', '', '', '', 18),
  (3, 1, 'vocabulary', '지난주', 'la semaine dernière', '', '', '', 19),
  (3, 1, 'vocabulary', '맞아요?', 'c''est bien ça ?', '', '', '', 20),
  (3, 1, 'expression', '전화번호가 뭐예요?', 'quel est votre numéro de téléphone ?', '', '', '', 1),
  (3, 1, 'expression', '전화번호가 어떻게 돼요?', 'quel est votre numéro ?', '', '', '', 2),
  (3, 1, 'expression', '전화번호 좀 가르쳐 주세요', 'puis-je avoir votre numéro ?', '', '', '', 3),
  (3, 1, 'expression', '그럼 또 봐요', 'à bientôt alors', '', '', '', 4),
  (3, 1, 'grammar', '이/가', 'Indique le sujet grammatical de la phrase', 'Indique le sujet grammatical de la phrase', '이 après consonne, 가 après voyelle. 나+가=내가, 저+가=제가, 누구+가=누가', '꽃이 예뻐요 (Les fleurs sont belles) / 마크 씨가 운동해요 (Mark fait du sport)', 1),
  (3, 1, 'grammar', '이 아니에요/가 아니에요', 'Exprime la négation d''un nom (= ce n''est pas ~)', 'Exprime la négation d''un nom (= ce n''est pas ~)', '이 아니에요 après consonne, 가 아니에요 après voyelle', '여기는 사무실이 아니에요 (Ce n''est pas un bureau) / 커피가 아니에요 (Ce n''est pas du café)', 2),
  (4, 1, 'vocabulary', '침대', 'lit', '', '', '', 1),
  (4, 1, 'vocabulary', '의자', 'chaise', '', '', '', 2),
  (4, 1, 'vocabulary', '책상', 'bureau (meuble)', '', '', '', 3),
  (4, 1, 'vocabulary', '컴퓨터', 'ordinateur', '', '', '', 4),
  (4, 1, 'vocabulary', '소파', 'canapé', '', '', '', 5),
  (4, 1, 'vocabulary', '탁자', 'table basse', '', '', '', 6),
  (4, 1, 'vocabulary', '티브이', 'télévision', '', '', '', 7),
  (4, 1, 'vocabulary', '냉장고', 'réfrigérateur', '', '', '', 8),
  (4, 1, 'vocabulary', '위', 'sur / au-dessus', '', '', '', 9),
  (4, 1, 'vocabulary', '아래', 'sous / en-dessous', '', '', '', 10),
  (4, 1, 'vocabulary', '앞', 'devant', '', '', '', 11),
  (4, 1, 'vocabulary', '뒤', 'derrière', '', '', '', 12),
  (4, 1, 'vocabulary', '옆', 'à côté de', '', '', '', 13),
  (4, 1, 'vocabulary', '안', 'dans / à l''intérieur', '', '', '', 14),
  (4, 1, 'vocabulary', '밖', 'dehors / à l''extérieur', '', '', '', 15),
  (4, 1, 'vocabulary', '지갑', 'portefeuille', '', '', '', 16),
  (4, 1, 'vocabulary', '가방', 'sac', '', '', '', 17),
  (4, 1, 'vocabulary', '핸드폰', 'téléphone portable', '', '', '', 18),
  (4, 1, 'vocabulary', '책', 'livre', '', '', '', 19),
  (4, 1, 'vocabulary', '안경', 'lunettes', '', '', '', 20),
  (4, 1, 'vocabulary', '모자', 'chapeau / casquette', '', '', '', 21),
  (4, 1, 'vocabulary', '공책', 'cahier', '', '', '', 22),
  (4, 1, 'vocabulary', '노트북', 'ordinateur portable', '', '', '', 23),
  (4, 1, 'vocabulary', '지하철역', 'station de métro', '', '', '', 24),
  (4, 1, 'vocabulary', '혹시', 'peut-être / au cas où', '', '', '', 25),
  (4, 1, 'vocabulary', '여보세요', 'allô', '', '', '', 26),
  (4, 1, 'vocabulary', '정말 다행이에요', 'c''est un soulagement', '', '', '', 27),
  (4, 1, 'vocabulary', '유에스비', 'clé USB', '', '', '', 28),
  (4, 1, 'vocabulary', '서랍', 'tiroir', '', '', '', 29),
  (4, 1, 'expression', '~에 있어요/없어요', 'il y a ~ / il n''y a pas de ~ (à/dans)', '', '', '', 1),
  (4, 1, 'expression', '~이/가 어디에 있어요?', 'où est ~ ?', '', '', '', 2),
  (4, 1, 'expression', '잠깐만요', 'un instant / attendez', '', '', '', 3),
  (4, 1, 'expression', '혹시 ~이/가 있어요?', 'est-ce qu''il y a ~ par hasard ?', '', '', '', 4),
  (4, 1, 'grammar', '에 있다/에 없다', 'Indique l''existence ou l''emplacement d''une personne ou d''un objet', 'Indique l''existence ou l''emplacement d''une personne ou d''un objet', 'Pour les supérieurs : 계시다 à la place de 있다', '안경이 책상 위에 있어요 (Les lunettes sont sur le bureau)', 1),
  (4, 1, 'grammar', '의', 'Indique la possession ou l''appartenance (= de / apostrophe s)', 'Indique la possession ou l''appartenance (= de / apostrophe s)', 'Souvent omis à l''oral. 저의→제, 나의→내, 너의→네', '로라 씨의 모자가 예뻐요 (Le chapeau de Laura est joli)', 2),
  (5, 1, 'vocabulary', '사과', 'pomme', '', '', '', 1),
  (5, 1, 'vocabulary', '오렌지', 'orange', '', '', '', 2),
  (5, 1, 'vocabulary', '바나나', 'banane', '', '', '', 3),
  (5, 1, 'vocabulary', '딸기', 'fraise', '', '', '', 4),
  (5, 1, 'vocabulary', '포도', 'raisin', '', '', '', 5),
  (5, 1, 'vocabulary', '수박', 'pastèque', '', '', '', 6),
  (5, 1, 'vocabulary', '우유', 'lait', '', '', '', 7),
  (5, 1, 'vocabulary', '주스', 'jus', '', '', '', 8),
  (5, 1, 'vocabulary', '콜라', 'coca-cola', '', '', '', 9),
  (5, 1, 'vocabulary', '과자', 'biscuits / snack', '', '', '', 10),
  (5, 1, 'vocabulary', '빵', 'pain', '', '', '', 11),
  (5, 1, 'vocabulary', '케이크', 'gâteau', '', '', '', 12),
  (5, 1, 'vocabulary', '샌드위치', 'sandwich', '', '', '', 13),
  (5, 1, 'vocabulary', '햄버거', 'hamburger', '', '', '', 14),
  (5, 1, 'vocabulary', '치약', 'dentifrice', '', '', '', 15),
  (5, 1, 'vocabulary', '비누', 'savon', '', '', '', 16),
  (5, 1, 'vocabulary', '수건', 'serviette', '', '', '', 17),
  (5, 1, 'vocabulary', '하나', 'un (coréen)', '', '', '', 18),
  (5, 1, 'vocabulary', '둘', 'deux (coréen)', '', '', '', 19),
  (5, 1, 'vocabulary', '셋', 'trois (coréen)', '', '', '', 20),
  (5, 1, 'vocabulary', '넷', 'quatre (coréen)', '', '', '', 21),
  (5, 1, 'vocabulary', '다섯', 'cinq (coréen)', '', '', '', 22),
  (5, 1, 'vocabulary', '여섯', 'six (coréen)', '', '', '', 23),
  (5, 1, 'vocabulary', '일곱', 'sept (coréen)', '', '', '', 24),
  (5, 1, 'vocabulary', '여덟', 'huit (coréen)', '', '', '', 25),
  (5, 1, 'vocabulary', '아홉', 'neuf (coréen)', '', '', '', 26),
  (5, 1, 'vocabulary', '열', 'dix (coréen)', '', '', '', 27),
  (5, 1, 'vocabulary', '개', 'unité (objet)', '', '', '', 28),
  (5, 1, 'vocabulary', '명', 'unité (personne)', '', '', '', 29),
  (5, 1, 'vocabulary', '마리', 'unité (animal)', '', '', '', 30),
  (5, 1, 'vocabulary', '잔', 'unité (verre/tasse)', '', '', '', 31),
  (5, 1, 'vocabulary', '병', 'unité (bouteille)', '', '', '', 32),
  (5, 1, 'vocabulary', '권', 'unité (livre)', '', '', '', 33),
  (5, 1, 'vocabulary', '장', 'unité (feuille)', '', '', '', 34),
  (5, 1, 'vocabulary', '봉지', 'sachet', '', '', '', 35),
  (5, 1, 'vocabulary', '어서 오세요', 'bienvenue', '', '', '', 36),
  (5, 1, 'vocabulary', '맛있게 드세요', 'bon appétit (dit par le serveur)', '', '', '', 37),
  (5, 1, 'vocabulary', '또 오세요', 'revenez nous voir', '', '', '', 38),
  (5, 1, 'vocabulary', '특별히', 'particulièrement / spécialement', '', '', '', 39),
  (5, 1, 'expression', '뭘 드릴까요?', 'que puis-je vous donner / que désirez-vous ?', '', '', '', 1),
  (5, 1, 'expression', '몇 개 드릴까요?', 'combien en voulez-vous ?', '', '', '', 2),
  (5, 1, 'expression', '얼마예요?', 'combien ça coûte ?', '', '', '', 3),
  (5, 1, 'expression', '~하고 ~ 주세요', 'donnez-moi ~ et ~, s''il vous plaît', '', '', '', 4),
  (5, 1, 'expression', '여기 있습니다', 'voilà / c''est ici', '', '', '', 5),
  (5, 1, 'grammar', '하고', 'Relie deux noms (= et), indique aussi ''avec''', 'Relie deux noms (= et), indique aussi ''avec''', 'S''utilise avec toutes terminaisons. 와/과 plus formel', '빵하고 우유를 먹어요 (Je mange du pain et du lait) / 친구하고 가요 (J''y vais avec un ami)', 1),
  (5, 1, 'grammar', '단위 명사 (개, 명, 마리...)', 'Compteurs utilisés avec les nombres coréens selon la nature de l''objet compté', 'Compteurs utilisés avec les nombres coréens selon la nature de l''objet compté', '하나→한 개, 둘→두 개, 셋→세 개, 넷→네 개, 스물→스무 개', '사과 세 개 주세요 (Donnez-moi 3 pommes) / 학생 다섯 명 (5 étudiants)', 2),
  (6, 1, 'vocabulary', '비빔밥', 'bibimbap (riz aux légumes assortis)', '', '', '', 1),
  (6, 1, 'vocabulary', '냉면', 'naengmyeon (nouilles froides)', '', '', '', 2),
  (6, 1, 'vocabulary', '비빔냉면', 'bibim-naengmyeon (nouilles froides épicées)', '', '', '', 3),
  (6, 1, 'vocabulary', '물냉면', 'mul-naengmyeon (nouilles froides en bouillon)', '', '', '', 4),
  (6, 1, 'vocabulary', '김치찌개', 'kimchi jjigae (ragoût de kimchi)', '', '', '', 5),
  (6, 1, 'vocabulary', '된장찌개', 'doenjang jjigae (ragoût de pâte de soja)', '', '', '', 6),
  (6, 1, 'vocabulary', '불고기', 'bulgogi (boeuf grillé mariné)', '', '', '', 7),
  (6, 1, 'vocabulary', '삼계탕', 'samgyetang (soupe de poulet au ginseng)', '', '', '', 8),
  (6, 1, 'vocabulary', '잡채', 'japchae (nouilles de verre aux légumes)', '', '', '', 9),
  (6, 1, 'vocabulary', '김밥', 'gimbap (rouleau de riz)', '', '', '', 10),
  (6, 1, 'vocabulary', '떡볶이', 'tteokbokki (gâteau de riz épicé)', '', '', '', 11),
  (6, 1, 'vocabulary', '스파게티', 'spaghetti', '', '', '', 12),
  (6, 1, 'vocabulary', '피자', 'pizza', '', '', '', 13),
  (6, 1, 'vocabulary', '스테이크', 'steak', '', '', '', 14),
  (6, 1, 'vocabulary', '치킨', 'poulet frit', '', '', '', 15),
  (6, 1, 'vocabulary', '맛있다', 'être délicieux', '', '', '', 16),
  (6, 1, 'vocabulary', '맛없다', 'être mauvais', '', '', '', 17),
  (6, 1, 'vocabulary', '맵다', 'être épicé', '', '', '', 18),
  (6, 1, 'vocabulary', '달다', 'être sucré', '', '', '', 19),
  (6, 1, 'vocabulary', '짜다', 'être salé', '', '', '', 20),
  (6, 1, 'vocabulary', '쓰다', 'être amer', '', '', '', 21),
  (6, 1, 'vocabulary', '시다', 'être acide / aigre', '', '', '', 22),
  (6, 1, 'vocabulary', '좋아하다', 'aimer', '', '', '', 23),
  (6, 1, 'vocabulary', '싫어하다', 'ne pas aimer / détester', '', '', '', 24),
  (6, 1, 'vocabulary', '소고기', 'boeuf', '', '', '', 25),
  (6, 1, 'vocabulary', '고기', 'viande', '', '', '', 26),
  (6, 1, 'vocabulary', '다', 'tout / tous', '', '', '', 27),
  (6, 1, 'vocabulary', '그런데', 'mais / cependant', '', '', '', 28),
  (6, 1, 'vocabulary', '별로', 'pas vraiment / pas tellement', '', '', '', 29),
  (6, 1, 'vocabulary', '인분', 'portion (pour N personnes)', '', '', '', 30),
  (6, 1, 'expression', '무슨 음식을 좋아해요?', 'quel genre de nourriture aimez-vous ?', '', '', '', 1),
  (6, 1, 'expression', '~를/을 빼 주세요', 'retirez ~ s''il vous plaît', '', '', '', 2),
  (6, 1, 'expression', '여기요!', 'excusez-moi ! (appeler le serveur)', '', '', '', 3),
  (6, 1, 'expression', '~하나/하나 주세요', 'un(e) ~, s''il vous plaît', '', '', '', 4),
  (6, 1, 'expression', '알겠어요', 'd''accord / j''ai compris', '', '', '', 5),
  (6, 1, 'grammar', '을/를', 'Indique le complément d''objet direct de la phrase', 'Indique le complément d''objet direct de la phrase', '을 après consonne, 를 après voyelle. Peut être omis avec 명사+하다', '냉면을 좋아해요 (J''aime le naengmyeon) / 친구를 기다려요 (J''attends un ami)', 1),
  (6, 1, 'grammar', '안, -지 않다', 'Exprime la négation de l''action ou de l''état du sujet', 'Exprime la négation de l''action ou de l''état du sujet', '안 devant le verbe, -지 않아요 après. Ne s''utilise pas avec 알다/모르다/있다/없다', '운동을 안 해요 (Je ne fais pas de sport) / 맵지 않아요 (Ce n''est pas épicé)', 2),
  (7, 1, 'vocabulary', '일월', 'janvier', '', '', '', 1),
  (7, 1, 'vocabulary', '이월', 'février', '', '', '', 2),
  (7, 1, 'vocabulary', '삼월', 'mars', '', '', '', 3),
  (7, 1, 'vocabulary', '사월', 'avril', '', '', '', 4),
  (7, 1, 'vocabulary', '오월', 'mai', '', '', '', 5),
  (7, 1, 'vocabulary', '유월', 'juin', '', '', '', 6),
  (7, 1, 'vocabulary', '칠월', 'juillet', '', '', '', 7),
  (7, 1, 'vocabulary', '팔월', 'août', '', '', '', 8),
  (7, 1, 'vocabulary', '구월', 'septembre', '', '', '', 9),
  (7, 1, 'vocabulary', '시월', 'octobre', '', '', '', 10),
  (7, 1, 'vocabulary', '십일월', 'novembre', '', '', '', 11),
  (7, 1, 'vocabulary', '십이월', 'décembre', '', '', '', 12),
  (7, 1, 'vocabulary', '월요일', 'lundi', '', '', '', 13),
  (7, 1, 'vocabulary', '화요일', 'mardi', '', '', '', 14),
  (7, 1, 'vocabulary', '수요일', 'mercredi', '', '', '', 15),
  (7, 1, 'vocabulary', '목요일', 'jeudi', '', '', '', 16),
  (7, 1, 'vocabulary', '금요일', 'vendredi', '', '', '', 17),
  (7, 1, 'vocabulary', '토요일', 'samedi', '', '', '', 18),
  (7, 1, 'vocabulary', '일요일', 'dimanche', '', '', '', 19),
  (7, 1, 'vocabulary', '오전', 'matin / avant-midi', '', '', '', 20),
  (7, 1, 'vocabulary', '오후', 'après-midi', '', '', '', 21),
  (7, 1, 'vocabulary', '아침', 'matin', '', '', '', 22),
  (7, 1, 'vocabulary', '점심', 'déjeuner / midi', '', '', '', 23),
  (7, 1, 'vocabulary', '저녁', 'soir / dîner', '', '', '', 24),
  (7, 1, 'vocabulary', '오늘', 'aujourd''hui', '', '', '', 25),
  (7, 1, 'vocabulary', '내일', 'demain', '', '', '', 26),
  (7, 1, 'vocabulary', '어제', 'hier', '', '', '', 27),
  (7, 1, 'vocabulary', '이번 주', 'cette semaine', '', '', '', 28),
  (7, 1, 'vocabulary', '다음 주', 'la semaine prochaine', '', '', '', 29),
  (7, 1, 'vocabulary', '지난주', 'la semaine dernière', '', '', '', 30),
  (7, 1, 'vocabulary', '이번 달', 'ce mois-ci', '', '', '', 31),
  (7, 1, 'vocabulary', '생일', 'anniversaire', '', '', '', 32),
  (7, 1, 'vocabulary', '며칠', 'quel jour du mois', '', '', '', 33),
  (7, 1, 'vocabulary', '몇 시', 'quelle heure', '', '', '', 34),
  (7, 1, 'vocabulary', '분', 'minute', '', '', '', 35),
  (7, 1, 'vocabulary', '시작하다', 'commencer', '', '', '', 36),
  (7, 1, 'vocabulary', '끝나다', 'finir / se terminer', '', '', '', 37),
  (7, 1, 'vocabulary', '일찍', 'tôt', '', '', '', 38),
  (7, 1, 'vocabulary', '빨리', 'vite / rapidement', '', '', '', 39),
  (7, 1, 'vocabulary', '출발하다', 'partir / démarrer', '', '', '', 40),
  (7, 1, 'expression', '생일이 언제예요?', 'quand est votre anniversaire ?', '', '', '', 1),
  (7, 1, 'expression', '오늘은 며칠이에요?', 'quelle est la date d''aujourd''hui ?', '', '', '', 2),
  (7, 1, 'expression', '몇 시예요?', 'quelle heure est-il ?', '', '', '', 3),
  (7, 1, 'expression', '~시에 만나요', 'on se retrouve à ~ heures', '', '', '', 4),
  (7, 1, 'expression', '빨리 오세요', 'venez vite', '', '', '', 5),
  (7, 1, 'grammar', '에 (temps)', 'S''attache aux noms de temps pour indiquer quand une action se produit', 'S''attache aux noms de temps pour indiquer quand une action se produit', 'Ne s''utilise pas avec : 오늘, 어제, 내일, 그저께, 모레, 매일, 언제', '2시에 수업이 끝나요 (Le cours finit à 14h) / 월요일에 만나요 (On se voit lundi)', 1),
  (7, 1, 'grammar', '-으세요/-세요', 'S''attache aux verbes pour formuler une demande ou un ordre poli', 'S''attache aux verbes pour formuler une demande ou un ordre poli', '-으세요 après consonne (sauf ㄹ), -세요 après voyelle ou ㄹ. 먹다→드세요, 자다→주무세요', '잘 들으세요 (Écoutez bien) / 10분 후에 전화하세요 (Appelez dans 10 minutes)', 2),
  (8, 1, 'vocabulary', '공원', 'parc', '', '', '', 1),
  (8, 1, 'vocabulary', '병원', 'hôpital / clinique', '', '', '', 2),
  (8, 1, 'vocabulary', '시장', 'marché', '', '', '', 3),
  (8, 1, 'vocabulary', '공연장', 'salle de spectacle / concert', '', '', '', 4),
  (8, 1, 'vocabulary', '영화관', 'cinéma', '', '', '', 5),
  (8, 1, 'vocabulary', '백화점', 'grand magasin', '', '', '', 6),
  (8, 1, 'vocabulary', '편의점', 'supérette', '', '', '', 7),
  (8, 1, 'vocabulary', '수영장', 'piscine', '', '', '', 8),
  (8, 1, 'vocabulary', '은행', 'banque', '', '', '', 9),
  (8, 1, 'vocabulary', '테니스를 치다', 'jouer au tennis', '', '', '', 10),
  (8, 1, 'vocabulary', '낚시를 하다', 'pêcher', '', '', '', 11),
  (8, 1, 'vocabulary', '등산을 하다', 'faire de la randonnée', '', '', '', 12),
  (8, 1, 'vocabulary', '그림을 그리다', 'dessiner', '', '', '', 13),
  (8, 1, 'vocabulary', '축구를 하다', 'jouer au football', '', '', '', 14),
  (8, 1, 'vocabulary', '요리를 하다', 'cuisiner', '', '', '', 15),
  (8, 1, 'vocabulary', '기타를 치다', 'jouer de la guitare', '', '', '', 16),
  (8, 1, 'vocabulary', '사진을 찍다', 'prendre des photos', '', '', '', 17),
  (8, 1, 'vocabulary', '노래를 부르다', 'chanter', '', '', '', 18),
  (8, 1, 'vocabulary', '춤을 추다', 'danser', '', '', '', 19),
  (8, 1, 'vocabulary', '음악을 듣다', 'écouter de la musique', '', '', '', 20),
  (8, 1, 'vocabulary', '자전거를 타다', 'faire du vélo', '', '', '', 21),
  (8, 1, 'vocabulary', '비자를 신청하다', 'faire une demande de visa', '', '', '', 22),
  (8, 1, 'vocabulary', '한국어를 배우다', 'apprendre le coréen', '', '', '', 23),
  (8, 1, 'vocabulary', '케이팝', 'K-pop', '', '', '', 24),
  (8, 1, 'vocabulary', '공연을 보다', 'voir un spectacle', '', '', '', 25),
  (8, 1, 'vocabulary', '사인을 받다', 'obtenir un autographe', '', '', '', 26),
  (8, 1, 'vocabulary', '동대문시장', 'marché de Dongdaemun', '', '', '', 27),
  (8, 1, 'vocabulary', '명동', 'Myeongdong (quartier de Séoul)', '', '', '', 28),
  (8, 1, 'vocabulary', '어울리다', 'aller bien / être assorti', '', '', '', 29),
  (8, 1, 'vocabulary', '지난가을', 'l''automne dernier', '', '', '', 30),
  (8, 1, 'vocabulary', '작년', 'l''année dernière', '', '', '', 31),
  (8, 1, 'vocabulary', '행복하다', 'être heureux / heureuse', '', '', '', 32),
  (8, 1, 'expression', '주말에 뭐 했어요?', 'qu''avez-vous fait ce week-end ?', '', '', '', 1),
  (8, 1, 'expression', '어제 뭐 했어요?', 'qu''avez-vous fait hier ?', '', '', '', 2),
  (8, 1, 'expression', '어디에서 ~했어요?', 'où avez-vous ~ ?', '', '', '', 3),
  (8, 1, 'expression', '정말 재미있었어요', 'c''était vraiment amusant', '', '', '', 4),
  (8, 1, 'grammar', '에서', 'Indique le lieu où se déroule une action', 'Indique le lieu où se déroule une action', 'Différent de 에 qui indique la destination. 에서 = lieu d''action, 에 = lieu d''existence/destination', '카페에서 친구를 만났어요 (J''ai rencontré un ami au café)', 1),
  (8, 1, 'grammar', '-았어요/-었어요/-였어요', 'Décrit une action ou un état au passé', 'Décrit une action ou un état au passé', '았어요 si voyelle ㅏ/ㅗ, 었어요 sinon, 했어요 pour 하다. Passé de 이에요 = 이었어요/였어요', '지난 주말에 영화를 봤어요 (J''ai vu un film le week-end dernier)', 2),
  (9, 1, 'vocabulary', '취미', 'loisir / passe-temps', '', '', '', 1),
  (9, 1, 'vocabulary', '항상', 'toujours', '', '', '', 2),
  (9, 1, 'vocabulary', '가끔', 'de temps en temps', '', '', '', 3),
  (9, 1, 'vocabulary', '자주', 'souvent', '', '', '', 4),
  (9, 1, 'vocabulary', '별로 안', 'pas vraiment / pas tellement', '', '', '', 5),
  (9, 1, 'vocabulary', '거의 안', 'presque jamais', '', '', '', 6),
  (9, 1, 'vocabulary', '전혀 안', 'jamais (pas du tout)', '', '', '', 7),
  (9, 1, 'vocabulary', '만', 'seulement', '', '', '', 8),
  (9, 1, 'vocabulary', '볼링을 치다', 'jouer au bowling', '', '', '', 9),
  (9, 1, 'vocabulary', '탁구를 치다', 'jouer au ping-pong', '', '', '', 10),
  (9, 1, 'vocabulary', '수영하다', 'nager', '', '', '', 11),
  (9, 1, 'vocabulary', '요가를 하다', 'faire du yoga', '', '', '', 12),
  (9, 1, 'vocabulary', '골프를 치다', 'jouer au golf', '', '', '', 13),
  (9, 1, 'vocabulary', '농구를 하다', 'jouer au basket', '', '', '', 14),
  (9, 1, 'vocabulary', '야구를 하다', 'jouer au baseball', '', '', '', 15),
  (9, 1, 'vocabulary', '매일', 'tous les jours', '', '', '', 16),
  (9, 1, 'vocabulary', '주말', 'week-end', '', '', '', 17),
  (9, 1, 'vocabulary', '이따가', 'tout à l''heure / plus tard', '', '', '', 18),
  (9, 1, 'vocabulary', '미안해요', 'je suis désolé(e)', '', '', '', 19),
  (9, 1, 'vocabulary', '다른 약속이 있어요', 'j''ai un autre rendez-vous', '', '', '', 20),
  (9, 1, 'vocabulary', '다음에 꼭 같이 가요', 'on ira ensemble la prochaine fois', '', '', '', 21),
  (9, 1, 'expression', '취미가 뭐예요?', 'quel est votre passe-temps ?', '', '', '', 1),
  (9, 1, 'expression', '~를/을 좋아해요?', 'aimez-vous ~ ?', '', '', '', 2),
  (9, 1, 'expression', '같이 ~해요', 'faisons ~ ensemble', '', '', '', 3),
  (9, 1, 'expression', '시간 있어요?', 'avez-vous du temps ?', '', '', '', 4),
  (9, 1, 'expression', '아직 특별한 계획은 없어요', 'je n''ai pas encore de projets particuliers', '', '', '', 5),
  (9, 1, 'grammar', '-을 거예요/-ㄹ 거예요 (1)', 'Exprime un plan ou une action future', 'Exprime un plan ou une action future', '-을 거예요 après consonne, -ㄹ 거예요 après voyelle ou ㄹ', '내일 친구를 만날 거예요 (Je vais rencontrer un ami demain)', 1),
  (9, 1, 'grammar', '-아요/-어요/-여요 (2) suggestion', 'Utilisé pour faire des suggestions à quelqu''un d''autre (= on fait ~ ?)', 'Utilisé pour faire des suggestions à quelqu''un d''autre (= on fait ~ ?)', 'Même forme que le présent mais intonation montante-descendante plus prolongée', '같이 점심 먹어요 (On déjeune ensemble ?) / 저하고 가요 (Venez avec moi)', 2),
  (10, 1, 'vocabulary', '할아버지', 'grand-père', '', '', '', 1),
  (10, 1, 'vocabulary', '할머니', 'grand-mère', '', '', '', 2),
  (10, 1, 'vocabulary', '아버지', 'père', '', '', '', 3),
  (10, 1, 'vocabulary', '어머니', 'mère', '', '', '', 4),
  (10, 1, 'vocabulary', '오빠', 'grand frère (d''une fille)', '', '', '', 5),
  (10, 1, 'vocabulary', '형', 'grand frère (d''un garçon)', '', '', '', 6),
  (10, 1, 'vocabulary', '언니', 'grande sœur (d''une fille)', '', '', '', 7),
  (10, 1, 'vocabulary', '누나', 'grande sœur (d''un garçon)', '', '', '', 8),
  (10, 1, 'vocabulary', '남동생', 'petit frère', '', '', '', 9),
  (10, 1, 'vocabulary', '여동생', 'petite sœur', '', '', '', 10),
  (10, 1, 'vocabulary', '남편', 'mari', '', '', '', 11),
  (10, 1, 'vocabulary', '아내', 'femme / épouse', '', '', '', 12),
  (10, 1, 'vocabulary', '아들', 'fils', '', '', '', 13),
  (10, 1, 'vocabulary', '딸', 'fille', '', '', '', 14),
  (10, 1, 'vocabulary', '고모', 'tante (sœur du père)', '', '', '', 15),
  (10, 1, 'vocabulary', '이모', 'tante (sœur de la mère)', '', '', '', 16),
  (10, 1, 'vocabulary', '삼촌', 'oncle (frère du père)', '', '', '', 17),
  (10, 1, 'vocabulary', '외삼촌', 'oncle (frère de la mère)', '', '', '', 18),
  (10, 1, 'vocabulary', '성함', 'nom (honorifique)', '', '', '', 19),
  (10, 1, 'vocabulary', '연세', 'âge (honorifique)', '', '', '', 20),
  (10, 1, 'vocabulary', '생신', 'anniversaire (honorifique)', '', '', '', 21),
  (10, 1, 'vocabulary', '댁', 'maison (honorifique)', '', '', '', 22),
  (10, 1, 'vocabulary', '물고기', 'poisson', '', '', '', 23),
  (10, 1, 'vocabulary', '크다', 'être grand / gros', '', '', '', 24),
  (10, 1, 'vocabulary', '고궁', 'palais ancien', '', '', '', 25),
  (10, 1, 'vocabulary', '사진을 찍다', 'prendre une photo', '', '', '', 26),
  (10, 1, 'vocabulary', '체스를 두다', 'jouer aux échecs', '', '', '', 27),
  (10, 1, 'expression', '~하러 가다', 'aller pour faire ~', '', '', '', 1),
  (10, 1, 'expression', '성함이 어떻게 되세요?', 'quel est votre nom ?', '', '', '', 2),
  (10, 1, 'expression', '연세가 어떻게 되세요?', 'quel âge avez-vous ?', '', '', '', 3),
  (10, 1, 'expression', '~께서 ~하세요', '~ fait ~ (honorifique)', '', '', '', 4),
  (10, 1, 'grammar', '-으시-/-시-', 'Marque de respect envers le sujet de la phrase (= forme honorifique)', 'Marque de respect envers le sujet de la phrase (= forme honorifique)', '-으시- après consonne (sauf ㄹ), -시- après voyelle ou ㄹ. Verbes spéciaux : 있다→계시다, 자다→주무시다, 먹다→드시다', '선생님께서 학교에 계세요 (Le professeur est à l''école)', 1),
  (10, 1, 'grammar', '-으러 가다/-러 가다', 'Exprime le but du déplacement (= aller pour ~)', 'Exprime le but du déplacement (= aller pour ~)', '-으러 가다 après consonne, -러 가다 après voyelle ou ㄹ. Verbe de mouvement : 가다, 오다, 다니다', '밥을 먹으러 가요 (Je vais manger) / 책을 빌리러 도서관에 가요 (Je vais à la bibliothèque emprunter un livre)', 2),
  (11, 1, 'vocabulary', '기쁘다', 'être content(e) / joyeux', '', '', '', 1),
  (11, 1, 'vocabulary', '슬프다', 'être triste', '', '', '', 2),
  (11, 1, 'vocabulary', '행복하다', 'être heureux / heureuse', '', '', '', 3),
  (11, 1, 'vocabulary', '재미있다', 'être amusant / intéressant', '', '', '', 4),
  (11, 1, 'vocabulary', '재미없다', 'être ennuyeux / sans intérêt', '', '', '', 5),
  (11, 1, 'vocabulary', '무섭다', 'être effrayant', '', '', '', 6),
  (11, 1, 'vocabulary', '어렵다', 'être difficile', '', '', '', 7),
  (11, 1, 'vocabulary', '쉽다', 'être facile', '', '', '', 8),
  (11, 1, 'vocabulary', '귀엽다', 'être mignon(ne)', '', '', '', 9),
  (11, 1, 'vocabulary', '멋있다', 'être beau / stylé', '', '', '', 10),
  (11, 1, 'vocabulary', '예쁘다', 'être joli(e)', '', '', '', 11),
  (11, 1, 'vocabulary', '편리하다', 'être pratique / commode', '', '', '', 12),
  (11, 1, 'vocabulary', '불편하다', 'être inconfortable', '', '', '', 13),
  (11, 1, 'vocabulary', '친절하다', 'être aimable / gentil', '', '', '', 14),
  (11, 1, 'vocabulary', '핸드폰', 'téléphone portable', '', '', '', 15),
  (11, 1, 'vocabulary', '가볍다', 'être léger', '', '', '', 16),
  (11, 1, 'vocabulary', '무겁다', 'être lourd', '', '', '', 17),
  (11, 1, 'vocabulary', '빠르다', 'être rapide', '', '', '', 18),
  (11, 1, 'vocabulary', '느리다', 'être lent', '', '', '', 19),
  (11, 1, 'vocabulary', '넓다', 'être vaste / large', '', '', '', 20),
  (11, 1, 'vocabulary', '좁다', 'être étroit', '', '', '', 21),
  (11, 1, 'vocabulary', '뮤지컬', 'comédie musicale', '', '', '', 22),
  (11, 1, 'vocabulary', '첫사랑', 'premier amour', '', '', '', 23),
  (11, 1, 'vocabulary', '유명하다', 'être célèbre', '', '', '', 24),
  (11, 1, 'vocabulary', '나오다', 'sortir / apparaître', '', '', '', 25),
  (11, 1, 'vocabulary', '경기장', 'stade', '', '', '', 26),
  (11, 1, 'vocabulary', '월드컵', 'coupe du monde', '', '', '', 27),
  (11, 1, 'vocabulary', '그날', 'ce jour-là', '', '', '', 28),
  (11, 1, 'vocabulary', '정말 잘됐네요', 'c''est parfait / tant mieux', '', '', '', 29),
  (11, 1, 'expression', '~고 싶어요', 'je veux / j''aimerais ~', '', '', '', 1),
  (11, 1, 'expression', '미안해요. 다른 약속이 있어요', 'désolé(e), j''ai un autre rendez-vous', '', '', '', 2),
  (11, 1, 'expression', '다음에 꼭 같이 가요', 'on ira ensemble la prochaine fois', '', '', '', 3),
  (11, 1, 'expression', '몇 시에 만날까요?', 'à quelle heure se retrouve-t-on ?', '', '', '', 4),
  (11, 1, 'expression', '어디에서 만날까요?', 'où se retrouve-t-on ?', '', '', '', 5),
  (11, 1, 'grammar', '-고 싶다', 'Exprime le désir ou le souhait du locuteur (= vouloir ~)', 'Exprime le désir ou le souhait du locuteur (= vouloir ~)', '-고 싶어 하다 quand le sujet n''est pas la 1ère personne', '제주도로 여행을 가고 싶어요 (Je veux voyager à Jeju)', 1),
  (11, 1, 'grammar', '-을까요?/-ㄹ까요?', 'Demande l''avis ou la suggestion de l''interlocuteur (= est-ce qu''on ~ ? / je dois ~ ?)', 'Demande l''avis ou la suggestion de l''interlocuteur (= est-ce qu''on ~ ? / je dois ~ ?)', '-을까요 après consonne, -ㄹ까요 après voyelle ou ㄹ', '우리 여기에서 사진을 찍을까요? (Et si on prenait des photos ici ?) / 제가 예약할까요? (Dois-je faire une réservation ?)', 2),
  (12, 1, 'vocabulary', '봄', 'printemps', '', '', '', 1),
  (12, 1, 'vocabulary', '여름', 'été', '', '', '', 2),
  (12, 1, 'vocabulary', '가을', 'automne', '', '', '', 3),
  (12, 1, 'vocabulary', '겨울', 'hiver', '', '', '', 4),
  (12, 1, 'vocabulary', '맑다', 'être clair / ensoleillé', '', '', '', 5),
  (12, 1, 'vocabulary', '흐리다', 'être nuageux', '', '', '', 6),
  (12, 1, 'vocabulary', '비가 오다', 'pleuvoir', '', '', '', 7),
  (12, 1, 'vocabulary', '눈이 오다', 'neiger', '', '', '', 8),
  (12, 1, 'vocabulary', '바람이 불다', 'le vent souffle', '', '', '', 9),
  (12, 1, 'vocabulary', '덥다', 'avoir chaud', '', '', '', 10),
  (12, 1, 'vocabulary', '춥다', 'avoir froid', '', '', '', 11),
  (12, 1, 'vocabulary', '따뜻하다', 'être chaud / doux', '', '', '', 12),
  (12, 1, 'vocabulary', '쌀쌀하다', 'être frais / frisquet', '', '', '', 13),
  (12, 1, 'vocabulary', '장마', 'saison des pluies', '', '', '', 14),
  (12, 1, 'vocabulary', '태풍', 'typhon', '', '', '', 15),
  (12, 1, 'vocabulary', '겨울옷', 'vêtements d''hiver', '', '', '', 16),
  (12, 1, 'vocabulary', '선글라스', 'lunettes de soleil', '', '', '', 17),
  (12, 1, 'vocabulary', '모자', 'chapeau / casquette', '', '', '', 18),
  (12, 1, 'vocabulary', '우산', 'parapluie', '', '', '', 19),
  (12, 1, 'vocabulary', '선크림', 'crème solaire', '', '', '', 20),
  (12, 1, 'vocabulary', '그동안', 'entre-temps / pendant ce temps', '', '', '', 21),
  (12, 1, 'vocabulary', '실력', 'niveau / compétence', '', '', '', 22),
  (12, 1, 'vocabulary', '출장', 'voyage d''affaires', '', '', '', 23),
  (12, 1, 'vocabulary', '가지고 가다', 'emporter / apporter', '', '', '', 24),
  (12, 1, 'vocabulary', '서핑하다', 'surfer', '', '', '', 25),
  (12, 1, 'vocabulary', '팔빙수', 'patbingsu (dessert glacé coréen)', '', '', '', 26),
  (12, 1, 'expression', '날씨가 어때요?', 'quel temps fait-il ?', '', '', '', 1),
  (12, 1, 'expression', '~고 눈도 많이 올 거예요', 'il fera ~ et il neigera beaucoup', '', '', '', 2),
  (12, 1, 'expression', '~를 가지고 가세요', 'emportez ~', '', '', '', 3),
  (12, 1, 'expression', '아마 ~을 거예요', 'probablement / il va certainement ~', '', '', '', 4),
  (12, 1, 'grammar', '-고 (coordination)', 'Relie deux propositions de façon équivalente (= et), liste des actions/états', 'Relie deux propositions de façon équivalente (= et), liste des actions/états', 'S''utilise avec toutes terminaisons. Pour le passé possible avec -았/었-고', '바람이 많이 불고 추워요 (Il y a beaucoup de vent et il fait froid)', 1),
  (12, 1, 'grammar', '-을 거예요/-ㄹ 거예요 (2)', 'Exprime une déduction ou probabilité basée sur l''expérience passée', 'Exprime une déduction ou probabilité basée sur l''expérience passée', 'Même forme que (1) mais sens différent : supposition vs plan', '내일도 비가 올 거예요 (Il pleuvra probablement demain aussi)', 2),
  (13, 1, 'vocabulary', '빨간색', 'rouge', '', '', '', 1),
  (13, 1, 'vocabulary', '파란색', 'bleu', '', '', '', 2),
  (13, 1, 'vocabulary', '노란색', 'jaune', '', '', '', 3),
  (13, 1, 'vocabulary', '초록색/녹색', 'vert', '', '', '', 4),
  (13, 1, 'vocabulary', '까만색', 'noir', '', '', '', 5),
  (13, 1, 'vocabulary', '하얀색', 'blanc', '', '', '', 6),
  (13, 1, 'vocabulary', '분홍색', 'rose', '', '', '', 7),
  (13, 1, 'vocabulary', '회색', 'gris', '', '', '', 8),
  (13, 1, 'vocabulary', '보라색', 'violet', '', '', '', 9),
  (13, 1, 'vocabulary', '하늘색', 'bleu ciel', '', '', '', 10),
  (13, 1, 'vocabulary', '바지', 'pantalon', '', '', '', 11),
  (13, 1, 'vocabulary', '치마', 'jupe', '', '', '', 12),
  (13, 1, 'vocabulary', '원피스', 'robe', '', '', '', 13),
  (13, 1, 'vocabulary', '티셔츠', 't-shirt', '', '', '', 14),
  (13, 1, 'vocabulary', '코트', 'manteau', '', '', '', 15),
  (13, 1, 'vocabulary', '점퍼', 'veste', '', '', '', 16),
  (13, 1, 'vocabulary', '운동화', 'baskets', '', '', '', 17),
  (13, 1, 'vocabulary', '구두', 'chaussures habillées', '', '', '', 18),
  (13, 1, 'vocabulary', '장갑', 'gants', '', '', '', 19),
  (13, 1, 'vocabulary', '목도리', 'cache-nez / écharpe', '', '', '', 20),
  (13, 1, 'vocabulary', '양말', 'chaussettes', '', '', '', 21),
  (13, 1, 'vocabulary', '안경', 'lunettes', '', '', '', 22),
  (13, 1, 'vocabulary', '핸드백', 'sac à main', '', '', '', 23),
  (13, 1, 'vocabulary', '배낭', 'sac à dos', '', '', '', 24),
  (13, 1, 'vocabulary', '청바지', 'jean', '', '', '', 25),
  (13, 1, 'vocabulary', '정장', 'costume / tenue formelle', '', '', '', 26),
  (13, 1, 'vocabulary', '수영복', 'maillot de bain', '', '', '', 27),
  (13, 1, 'vocabulary', '입다', 'porter (vêtement)', '', '', '', 28),
  (13, 1, 'vocabulary', '신다', 'porter (chaussures)', '', '', '', 29),
  (13, 1, 'vocabulary', '쓰다', 'porter (chapeau/lunettes)', '', '', '', 30),
  (13, 1, 'vocabulary', '끼다', 'porter (gants)', '', '', '', 31),
  (13, 1, 'vocabulary', '인기가 많다', 'être populaire', '', '', '', 32),
  (13, 1, 'vocabulary', '어울리다', 'aller bien / être assorti', '', '', '', 33),
  (13, 1, 'vocabulary', '포장해 주세요', 'emballez-le/la s''il vous plaît', '', '', '', 34),
  (13, 1, 'expression', '무슨 색 ~를 찾으세요?', 'quelle couleur de ~ cherchez-vous ?', '', '', '', 1),
  (13, 1, 'expression', '~한테/께 선물할 거예요', 'je vais offrir un cadeau à ~', '', '', '', 2),
  (13, 1, 'expression', '이걸로 할게요', 'je prends celui-ci/celle-ci', '', '', '', 3),
  (13, 1, 'expression', '뭘 찾으세요?', 'que recherchez-vous ?', '', '', '', 4),
  (13, 1, 'expression', '~에게 선물로 주다', 'offrir comme cadeau à ~', '', '', '', 5),
  (13, 1, 'grammar', '한테, 한테(서)', '한테 : indique la cible de l''action du sujet (= à). 한테서 : indique la source (= de la part de)', '한테 : indique la cible de l''action du sujet (= à). 한테서 : indique la source (= de la part de)', 'Pour les supérieurs : 께 à la place de 한테, 한테서. Pour offrir à un supérieur : 드리다 à la place de 주다', '친구한테 선물을 줬어요 (J''ai offert un cadeau à mon ami) / 선생님께 꽃을 드렸어요 (J''ai offert des fleurs au professeur)', 1),
  (13, 1, 'grammar', '-지만', 'Exprime un contraste entre deux propositions (= mais)', 'Exprime un contraste entre deux propositions (= mais)', 'S''utilise avec tous les verbes et adjectifs quelle que soit la terminaison', '예쁘지만 좀 불편해요 (C''est joli mais un peu inconfortable)', 2),
  (14, 1, 'vocabulary', '머리가 아프다', 'avoir mal à la tête', '', '', '', 1),
  (14, 1, 'vocabulary', '배가 아프다', 'avoir mal au ventre', '', '', '', 2),
  (14, 1, 'vocabulary', '목이 아프다', 'avoir mal à la gorge', '', '', '', 3),
  (14, 1, 'vocabulary', '허리가 아프다', 'avoir mal au dos', '', '', '', 4),
  (14, 1, 'vocabulary', '다리가 아프다', 'avoir mal à la jambe', '', '', '', 5),
  (14, 1, 'vocabulary', '이가 아프다', 'avoir mal aux dents', '', '', '', 6),
  (14, 1, 'vocabulary', '기침이 나다', 'tousser', '', '', '', 7),
  (14, 1, 'vocabulary', '열이 나다', 'avoir de la fièvre', '', '', '', 8),
  (14, 1, 'vocabulary', '콧물이 나다', 'avoir le nez qui coule', '', '', '', 9),
  (14, 1, 'vocabulary', '눈물이 나다', 'avoir les yeux qui pleurent', '', '', '', 10),
  (14, 1, 'vocabulary', '배탈이 나다', 'avoir une intoxication alimentaire', '', '', '', 11),
  (14, 1, 'vocabulary', '눈병이 나다', 'avoir une infection oculaire', '', '', '', 12),
  (14, 1, 'vocabulary', '감기에 걸리다', 'attraper un rhume', '', '', '', 13),
  (14, 1, 'vocabulary', '이사를 하다', 'déménager', '', '', '', 14),
  (14, 1, 'vocabulary', '모임', 'réunion / rassemblement', '', '', '', 15),
  (14, 1, 'vocabulary', '대회에 나가다', 'participer à un concours', '', '', '', 16),
  (14, 1, 'vocabulary', '공연을 하다', 'faire un spectacle', '', '', '', 17),
  (14, 1, 'vocabulary', '불꽃 축제', 'festival de feux d''artifice', '', '', '', 18),
  (14, 1, 'vocabulary', '말하기 대회', 'concours d''expression orale', '', '', '', 19),
  (14, 1, 'vocabulary', '피곤하다', 'être fatigué(e)', '', '', '', 20),
  (14, 1, 'vocabulary', '늦다', 'être en retard', '', '', '', 21),
  (14, 1, 'vocabulary', '지각하다', 'être en retard à l''école/travail', '', '', '', 22),
  (14, 1, 'vocabulary', '잃어버리다', 'perdre', '', '', '', 23),
  (14, 1, 'vocabulary', '고장나다', 'être en panne', '', '', '', 24),
  (14, 1, 'expression', '왜 ~ 못 했어요?', 'pourquoi n''avez-vous pas pu ~ ?', '', '', '', 1),
  (14, 1, 'expression', '~아서/어서 못 ~했어요', 'j''ai ~ alors je n''ai pas pu ~', '', '', '', 2),
  (14, 1, 'expression', '어떡하죠?', 'que dois-je faire ? / c''est embêtant', '', '', '', 3),
  (14, 1, 'expression', '약속 날짜를 바꿀까요?', 'devrions-nous changer la date ?', '', '', '', 4),
  (14, 1, 'expression', '~에서 뭐 사 왔어요?', 'qu''avez-vous acheté en ~?', '', '', '', 5),
  (14, 1, 'grammar', '-아서/-어서/-여서 (1)', 'Exprime la cause ou la raison de la proposition suivante', 'Exprime la cause ou la raison de la proposition suivante', 'Ne s''utilise pas avec les marqueurs de temps (-았/었-). Pas d''impératif ou suggestif dans la proposition suivante', '날씨가 좋아서 산책하러 가요 (Il fait beau alors je vais me promener) / 피곤해서 일찍 잤어요 (J''étais fatigué alors je me suis couché tôt)', 1),
  (14, 1, 'grammar', '못', 'Exprime l''incapacité due à des facteurs externes ou un manque de compétence', 'Exprime l''incapacité due à des facteurs externes ou un manque de compétence', '못 devant le verbe. Pour 명사+하다 : 명사+못+하다', '약속이 있어서 못 가요 (J''ai un rendez-vous donc je ne peux pas y aller) / 다리를 다쳐서 운동을 못 해요 (Je me suis blessé à la jambe donc je ne peux pas faire de sport)', 2);
